# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hayes/Stores/repos/bluefalconhd/xniff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hayes/Stores/repos/bluefalconhd/xniff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hayes/Stores/repos/bluefalconhd/xniff/CMakeFiles /Users/hayes/Stores/repos/bluefalconhd/xniff//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hayes/Stores/repos/bluefalconhd/xniff/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/hayes/Stores/repos/bluefalconhd/xniff/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xniff

# Build rule for target.
xniff: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xniff
.PHONY : xniff

# fast build rule for target.
xniff/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/build
.PHONY : xniff/fast

#=============================================================================
# Target rules for targets named xniff-hooks

# Build rule for target.
xniff-hooks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xniff-hooks
.PHONY : xniff-hooks

# fast build rule for target.
xniff-hooks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/build
.PHONY : xniff-hooks/fast

#=============================================================================
# Target rules for targets named xniff-cli

# Build rule for target.
xniff-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xniff-cli
.PHONY : xniff-cli

# fast build rule for target.
xniff-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/build
.PHONY : xniff-cli/fast

#=============================================================================
# Target rules for targets named xniff-test

# Build rule for target.
xniff-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xniff-test
.PHONY : xniff-test

# fast build rule for target.
xniff-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/build
.PHONY : xniff-test/fast

#=============================================================================
# Target rules for targets named xniff-xpc-stress

# Build rule for target.
xniff-xpc-stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xniff-xpc-stress
.PHONY : xniff-xpc-stress

# fast build rule for target.
xniff-xpc-stress/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-xpc-stress.dir/build.make CMakeFiles/xniff-xpc-stress.dir/build
.PHONY : xniff-xpc-stress/fast

#=============================================================================
# Target rules for targets named xpcdesert

# Build rule for target.
xpcdesert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xpcdesert
.PHONY : xpcdesert

# fast build rule for target.
xpcdesert/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/build
.PHONY : xpcdesert/fast

#=============================================================================
# Target rules for targets named xpcdesert-cli

# Build rule for target.
xpcdesert-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xpcdesert-cli
.PHONY : xpcdesert-cli

# fast build rule for target.
xpcdesert-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert-cli.dir/build.make CMakeFiles/xpcdesert-cli.dir/build
.PHONY : xpcdesert-cli/fast

Sources/libxniff/src/dylib_inject_stub.o: Sources/libxniff/src/dylib_inject_stub.S.o
.PHONY : Sources/libxniff/src/dylib_inject_stub.o

# target to build an object file
Sources/libxniff/src/dylib_inject_stub.S.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/dylib_inject_stub.S.o
.PHONY : Sources/libxniff/src/dylib_inject_stub.S.o

Sources/libxniff/src/inject.o: Sources/libxniff/src/inject.c.o
.PHONY : Sources/libxniff/src/inject.o

# target to build an object file
Sources/libxniff/src/inject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/inject.c.o
.PHONY : Sources/libxniff/src/inject.c.o

Sources/libxniff/src/inject.i: Sources/libxniff/src/inject.c.i
.PHONY : Sources/libxniff/src/inject.i

# target to preprocess a source file
Sources/libxniff/src/inject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/inject.c.i
.PHONY : Sources/libxniff/src/inject.c.i

Sources/libxniff/src/inject.s: Sources/libxniff/src/inject.c.s
.PHONY : Sources/libxniff/src/inject.s

# target to generate assembly for a file
Sources/libxniff/src/inject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/inject.c.s
.PHONY : Sources/libxniff/src/inject.c.s

Sources/libxniff/src/macho_symbols.o: Sources/libxniff/src/macho_symbols.c.o
.PHONY : Sources/libxniff/src/macho_symbols.o

# target to build an object file
Sources/libxniff/src/macho_symbols.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/macho_symbols.c.o
.PHONY : Sources/libxniff/src/macho_symbols.c.o

Sources/libxniff/src/macho_symbols.i: Sources/libxniff/src/macho_symbols.c.i
.PHONY : Sources/libxniff/src/macho_symbols.i

# target to preprocess a source file
Sources/libxniff/src/macho_symbols.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/macho_symbols.c.i
.PHONY : Sources/libxniff/src/macho_symbols.c.i

Sources/libxniff/src/macho_symbols.s: Sources/libxniff/src/macho_symbols.c.s
.PHONY : Sources/libxniff/src/macho_symbols.s

# target to generate assembly for a file
Sources/libxniff/src/macho_symbols.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/macho_symbols.c.s
.PHONY : Sources/libxniff/src/macho_symbols.c.s

Sources/libxniff/src/patch.o: Sources/libxniff/src/patch.c.o
.PHONY : Sources/libxniff/src/patch.o

# target to build an object file
Sources/libxniff/src/patch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/patch.c.o
.PHONY : Sources/libxniff/src/patch.c.o

Sources/libxniff/src/patch.i: Sources/libxniff/src/patch.c.i
.PHONY : Sources/libxniff/src/patch.i

# target to preprocess a source file
Sources/libxniff/src/patch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/patch.c.i
.PHONY : Sources/libxniff/src/patch.c.i

Sources/libxniff/src/patch.s: Sources/libxniff/src/patch.c.s
.PHONY : Sources/libxniff/src/patch.s

# target to generate assembly for a file
Sources/libxniff/src/patch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff.dir/build.make CMakeFiles/xniff.dir/Sources/libxniff/src/patch.c.s
.PHONY : Sources/libxniff/src/patch.c.s

Sources/shared/xniff_ipc.o: Sources/shared/xniff_ipc.c.o
.PHONY : Sources/shared/xniff_ipc.o

# target to build an object file
Sources/shared/xniff_ipc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/shared/xniff_ipc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/shared/xniff_ipc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/shared/xniff_ipc.c.o
.PHONY : Sources/shared/xniff_ipc.c.o

Sources/shared/xniff_ipc.i: Sources/shared/xniff_ipc.c.i
.PHONY : Sources/shared/xniff_ipc.i

# target to preprocess a source file
Sources/shared/xniff_ipc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/shared/xniff_ipc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/shared/xniff_ipc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/shared/xniff_ipc.c.i
.PHONY : Sources/shared/xniff_ipc.c.i

Sources/shared/xniff_ipc.s: Sources/shared/xniff_ipc.c.s
.PHONY : Sources/shared/xniff_ipc.s

# target to generate assembly for a file
Sources/shared/xniff_ipc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/shared/xniff_ipc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/shared/xniff_ipc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/shared/xniff_ipc.c.s
.PHONY : Sources/shared/xniff_ipc.c.s

Sources/xniff-cli/main.o: Sources/xniff-cli/main.c.o
.PHONY : Sources/xniff-cli/main.o

# target to build an object file
Sources/xniff-cli/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/xniff-cli/main.c.o
.PHONY : Sources/xniff-cli/main.c.o

Sources/xniff-cli/main.i: Sources/xniff-cli/main.c.i
.PHONY : Sources/xniff-cli/main.i

# target to preprocess a source file
Sources/xniff-cli/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/xniff-cli/main.c.i
.PHONY : Sources/xniff-cli/main.c.i

Sources/xniff-cli/main.s: Sources/xniff-cli/main.c.s
.PHONY : Sources/xniff-cli/main.s

# target to generate assembly for a file
Sources/xniff-cli/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-cli.dir/build.make CMakeFiles/xniff-cli.dir/Sources/xniff-cli/main.c.s
.PHONY : Sources/xniff-cli/main.c.s

Sources/xniff-hooks/frida_gum_interceptor.o: Sources/xniff-hooks/frida_gum_interceptor.c.o
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.o

# target to build an object file
Sources/xniff-hooks/frida_gum_interceptor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/frida_gum_interceptor.c.o
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.c.o

Sources/xniff-hooks/frida_gum_interceptor.i: Sources/xniff-hooks/frida_gum_interceptor.c.i
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.i

# target to preprocess a source file
Sources/xniff-hooks/frida_gum_interceptor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/frida_gum_interceptor.c.i
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.c.i

Sources/xniff-hooks/frida_gum_interceptor.s: Sources/xniff-hooks/frida_gum_interceptor.c.s
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.s

# target to generate assembly for a file
Sources/xniff-hooks/frida_gum_interceptor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/frida_gum_interceptor.c.s
.PHONY : Sources/xniff-hooks/frida_gum_interceptor.c.s

Sources/xniff-hooks/xniff_hooks_api.o: Sources/xniff-hooks/xniff_hooks_api.c.o
.PHONY : Sources/xniff-hooks/xniff_hooks_api.o

# target to build an object file
Sources/xniff-hooks/xniff_hooks_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xniff_hooks_api.c.o
.PHONY : Sources/xniff-hooks/xniff_hooks_api.c.o

Sources/xniff-hooks/xniff_hooks_api.i: Sources/xniff-hooks/xniff_hooks_api.c.i
.PHONY : Sources/xniff-hooks/xniff_hooks_api.i

# target to preprocess a source file
Sources/xniff-hooks/xniff_hooks_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xniff_hooks_api.c.i
.PHONY : Sources/xniff-hooks/xniff_hooks_api.c.i

Sources/xniff-hooks/xniff_hooks_api.s: Sources/xniff-hooks/xniff_hooks_api.c.s
.PHONY : Sources/xniff-hooks/xniff_hooks_api.s

# target to generate assembly for a file
Sources/xniff-hooks/xniff_hooks_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xniff_hooks_api.c.s
.PHONY : Sources/xniff-hooks/xniff_hooks_api.c.s

Sources/xniff-hooks/xpc_highlevel_hooks.o: Sources/xniff-hooks/xpc_highlevel_hooks.c.o
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.o

# target to build an object file
Sources/xniff-hooks/xpc_highlevel_hooks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_highlevel_hooks.c.o
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.c.o

Sources/xniff-hooks/xpc_highlevel_hooks.i: Sources/xniff-hooks/xpc_highlevel_hooks.c.i
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.i

# target to preprocess a source file
Sources/xniff-hooks/xpc_highlevel_hooks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_highlevel_hooks.c.i
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.c.i

Sources/xniff-hooks/xpc_highlevel_hooks.s: Sources/xniff-hooks/xpc_highlevel_hooks.c.s
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.s

# target to generate assembly for a file
Sources/xniff-hooks/xpc_highlevel_hooks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_highlevel_hooks.c.s
.PHONY : Sources/xniff-hooks/xpc_highlevel_hooks.c.s

Sources/xniff-hooks/xpc_hooks.o: Sources/xniff-hooks/xpc_hooks.c.o
.PHONY : Sources/xniff-hooks/xpc_hooks.o

# target to build an object file
Sources/xniff-hooks/xpc_hooks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_hooks.c.o
.PHONY : Sources/xniff-hooks/xpc_hooks.c.o

Sources/xniff-hooks/xpc_hooks.i: Sources/xniff-hooks/xpc_hooks.c.i
.PHONY : Sources/xniff-hooks/xpc_hooks.i

# target to preprocess a source file
Sources/xniff-hooks/xpc_hooks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_hooks.c.i
.PHONY : Sources/xniff-hooks/xpc_hooks.c.i

Sources/xniff-hooks/xpc_hooks.s: Sources/xniff-hooks/xpc_hooks.c.s
.PHONY : Sources/xniff-hooks/xpc_hooks.s

# target to generate assembly for a file
Sources/xniff-hooks/xpc_hooks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-hooks.dir/build.make CMakeFiles/xniff-hooks.dir/Sources/xniff-hooks/xpc_hooks.c.s
.PHONY : Sources/xniff-hooks/xpc_hooks.c.s

Sources/xniff-tests/main.o: Sources/xniff-tests/main.c.o
.PHONY : Sources/xniff-tests/main.o

# target to build an object file
Sources/xniff-tests/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/xniff-tests/main.c.o
.PHONY : Sources/xniff-tests/main.c.o

Sources/xniff-tests/main.i: Sources/xniff-tests/main.c.i
.PHONY : Sources/xniff-tests/main.i

# target to preprocess a source file
Sources/xniff-tests/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/xniff-tests/main.c.i
.PHONY : Sources/xniff-tests/main.c.i

Sources/xniff-tests/main.s: Sources/xniff-tests/main.c.s
.PHONY : Sources/xniff-tests/main.s

# target to generate assembly for a file
Sources/xniff-tests/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-test.dir/build.make CMakeFiles/xniff-test.dir/Sources/xniff-tests/main.c.s
.PHONY : Sources/xniff-tests/main.c.s

Sources/xniff-xpc-stress/main.o: Sources/xniff-xpc-stress/main.c.o
.PHONY : Sources/xniff-xpc-stress/main.o

# target to build an object file
Sources/xniff-xpc-stress/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-xpc-stress.dir/build.make CMakeFiles/xniff-xpc-stress.dir/Sources/xniff-xpc-stress/main.c.o
.PHONY : Sources/xniff-xpc-stress/main.c.o

Sources/xniff-xpc-stress/main.i: Sources/xniff-xpc-stress/main.c.i
.PHONY : Sources/xniff-xpc-stress/main.i

# target to preprocess a source file
Sources/xniff-xpc-stress/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-xpc-stress.dir/build.make CMakeFiles/xniff-xpc-stress.dir/Sources/xniff-xpc-stress/main.c.i
.PHONY : Sources/xniff-xpc-stress/main.c.i

Sources/xniff-xpc-stress/main.s: Sources/xniff-xpc-stress/main.c.s
.PHONY : Sources/xniff-xpc-stress/main.s

# target to generate assembly for a file
Sources/xniff-xpc-stress/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xniff-xpc-stress.dir/build.make CMakeFiles/xniff-xpc-stress.dir/Sources/xniff-xpc-stress/main.c.s
.PHONY : Sources/xniff-xpc-stress/main.c.s

Sources/xpcdesert/stream.o: Sources/xpcdesert/stream.c.o
.PHONY : Sources/xpcdesert/stream.o

# target to build an object file
Sources/xpcdesert/stream.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/stream.c.o
.PHONY : Sources/xpcdesert/stream.c.o

Sources/xpcdesert/stream.i: Sources/xpcdesert/stream.c.i
.PHONY : Sources/xpcdesert/stream.i

# target to preprocess a source file
Sources/xpcdesert/stream.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/stream.c.i
.PHONY : Sources/xpcdesert/stream.c.i

Sources/xpcdesert/stream.s: Sources/xpcdesert/stream.c.s
.PHONY : Sources/xpcdesert/stream.s

# target to generate assembly for a file
Sources/xpcdesert/stream.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/stream.c.s
.PHONY : Sources/xpcdesert/stream.c.s

Sources/xpcdesert/xpcdesert.o: Sources/xpcdesert/xpcdesert.c.o
.PHONY : Sources/xpcdesert/xpcdesert.o

# target to build an object file
Sources/xpcdesert/xpcdesert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/xpcdesert.c.o
.PHONY : Sources/xpcdesert/xpcdesert.c.o

Sources/xpcdesert/xpcdesert.i: Sources/xpcdesert/xpcdesert.c.i
.PHONY : Sources/xpcdesert/xpcdesert.i

# target to preprocess a source file
Sources/xpcdesert/xpcdesert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/xpcdesert.c.i
.PHONY : Sources/xpcdesert/xpcdesert.c.i

Sources/xpcdesert/xpcdesert.s: Sources/xpcdesert/xpcdesert.c.s
.PHONY : Sources/xpcdesert/xpcdesert.s

# target to generate assembly for a file
Sources/xpcdesert/xpcdesert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert.dir/build.make CMakeFiles/xpcdesert.dir/Sources/xpcdesert/xpcdesert.c.s
.PHONY : Sources/xpcdesert/xpcdesert.c.s

Sources/xpcdesert/xpcdesert_cli.o: Sources/xpcdesert/xpcdesert_cli.c.o
.PHONY : Sources/xpcdesert/xpcdesert_cli.o

# target to build an object file
Sources/xpcdesert/xpcdesert_cli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert-cli.dir/build.make CMakeFiles/xpcdesert-cli.dir/Sources/xpcdesert/xpcdesert_cli.c.o
.PHONY : Sources/xpcdesert/xpcdesert_cli.c.o

Sources/xpcdesert/xpcdesert_cli.i: Sources/xpcdesert/xpcdesert_cli.c.i
.PHONY : Sources/xpcdesert/xpcdesert_cli.i

# target to preprocess a source file
Sources/xpcdesert/xpcdesert_cli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert-cli.dir/build.make CMakeFiles/xpcdesert-cli.dir/Sources/xpcdesert/xpcdesert_cli.c.i
.PHONY : Sources/xpcdesert/xpcdesert_cli.c.i

Sources/xpcdesert/xpcdesert_cli.s: Sources/xpcdesert/xpcdesert_cli.c.s
.PHONY : Sources/xpcdesert/xpcdesert_cli.s

# target to generate assembly for a file
Sources/xpcdesert/xpcdesert_cli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xpcdesert-cli.dir/build.make CMakeFiles/xpcdesert-cli.dir/Sources/xpcdesert/xpcdesert_cli.c.s
.PHONY : Sources/xpcdesert/xpcdesert_cli.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xniff"
	@echo "... xniff-cli"
	@echo "... xniff-hooks"
	@echo "... xniff-test"
	@echo "... xniff-xpc-stress"
	@echo "... xpcdesert"
	@echo "... xpcdesert-cli"
	@echo "... Sources/libxniff/src/dylib_inject_stub.o"
	@echo "... Sources/libxniff/src/inject.o"
	@echo "... Sources/libxniff/src/inject.i"
	@echo "... Sources/libxniff/src/inject.s"
	@echo "... Sources/libxniff/src/macho_symbols.o"
	@echo "... Sources/libxniff/src/macho_symbols.i"
	@echo "... Sources/libxniff/src/macho_symbols.s"
	@echo "... Sources/libxniff/src/patch.o"
	@echo "... Sources/libxniff/src/patch.i"
	@echo "... Sources/libxniff/src/patch.s"
	@echo "... Sources/shared/xniff_ipc.o"
	@echo "... Sources/shared/xniff_ipc.i"
	@echo "... Sources/shared/xniff_ipc.s"
	@echo "... Sources/xniff-cli/main.o"
	@echo "... Sources/xniff-cli/main.i"
	@echo "... Sources/xniff-cli/main.s"
	@echo "... Sources/xniff-hooks/frida_gum_interceptor.o"
	@echo "... Sources/xniff-hooks/frida_gum_interceptor.i"
	@echo "... Sources/xniff-hooks/frida_gum_interceptor.s"
	@echo "... Sources/xniff-hooks/xniff_hooks_api.o"
	@echo "... Sources/xniff-hooks/xniff_hooks_api.i"
	@echo "... Sources/xniff-hooks/xniff_hooks_api.s"
	@echo "... Sources/xniff-hooks/xpc_highlevel_hooks.o"
	@echo "... Sources/xniff-hooks/xpc_highlevel_hooks.i"
	@echo "... Sources/xniff-hooks/xpc_highlevel_hooks.s"
	@echo "... Sources/xniff-hooks/xpc_hooks.o"
	@echo "... Sources/xniff-hooks/xpc_hooks.i"
	@echo "... Sources/xniff-hooks/xpc_hooks.s"
	@echo "... Sources/xniff-tests/main.o"
	@echo "... Sources/xniff-tests/main.i"
	@echo "... Sources/xniff-tests/main.s"
	@echo "... Sources/xniff-xpc-stress/main.o"
	@echo "... Sources/xniff-xpc-stress/main.i"
	@echo "... Sources/xniff-xpc-stress/main.s"
	@echo "... Sources/xpcdesert/stream.o"
	@echo "... Sources/xpcdesert/stream.i"
	@echo "... Sources/xpcdesert/stream.s"
	@echo "... Sources/xpcdesert/xpcdesert.o"
	@echo "... Sources/xpcdesert/xpcdesert.i"
	@echo "... Sources/xpcdesert/xpcdesert.s"
	@echo "... Sources/xpcdesert/xpcdesert_cli.o"
	@echo "... Sources/xpcdesert/xpcdesert_cli.i"
	@echo "... Sources/xpcdesert/xpcdesert_cli.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/hayes/Stores/repos/bluefalconhd/xniff/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

